version: '3.8'

services:
  spring_shop:
    container_name: spring_shop
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - spring-network
    environment:
      SPRING_PROFILES_ACTIVE: test

networks:
  spring-network:
